### ISSUE TITLE
Executables are executable

### ISSUE THREAD

**Issue by helo1223** [Bocko/Link2Folder#4]
https://github.com/Bocko/Link2Folder/blob/1455496374e19da738f79ee40709cc19947222c5/Program.cs#L161

Using the `link2folder://C:\Users\dagfe\Desktop\run.bat` link, the system runs the bat file.

**Comment by Bocko** [comment]
@helo1223 this issue should be fixed with 1dc3b2ace4d9f0e7fda0f91813d9fe7b87ecd0a5
Can you please test it?

**Comment by helo1223** [comment]
On the current release, Windows Defender detects Link2Folder as Trojan:Script/Phonzy.B!ml

Please  fix

**Comment by helo1223** [comment]
Windows Defender issue fixed :)

Executables no longer execute, hurray
